### ISSUE TITLE
Перевод cheatsheet

### ISSUE THREAD

**Issue by slider23** [LaravelRUS/laravel.ru#1]
Надо закончить перевод http://cheats.jesse-obrien.ca . Файл лежит в `app/views/cheatsheet/cheatsheet.php`

**Comment by SCIF** [comment]
Я могу это сделать. Требуется ли поднимать локальную версию для этого или достаточно просто перевести комменты, а дальше уже не моя забота будет?

**Comment by slider23** [comment]
Можно прямо на гитхабе редактировать: https://github.com/LaravelRUS/laravel.ru/blob/master/app/views/cheatsheet/cheatsheet.php

**Comment by slider23** [comment]
UPD прямо на гитхабе уже лучше не редактировать, так как у нас пошел активный девелопинг, лучше подключаться к разработке на https://trello.com/b/lDqJrw8x/-
