### ISSUE TITLE
Битая ссылка на странице http://laravel.su/articles/rus-documentation-contribution-guide

### ISSUE THREAD

**Issue by bigperson** [LaravelRUS/laravel.ru#13]
На странице http://laravel.su/articles/rus-documentation-contribution-guide битая ссылка http://image.prntscr.com/image/dfa127b8ec7a4363b0658bee45cd3004.png, которая должна вести на http://laravel.su/docs/status

**Comment by vladshcherbin** [comment]
Fixed 😉
