### ISSUE TITLE
404 ошибка при попытке открыть документацию

### ISSUE THREAD

**Issue by bigperson** [LaravelRUS/laravel.ru#14]
404 ошибка при попытке открыть документацию в разделе eloquent
http://image.prntscr.com/image/27a661908b28489084670fe71314daf8.png

http://laravel.su/docs/5.2/eloquent-relationships
http://laravel.su/docs/5.2/eloquent-collections
http://laravel.su/docs/5.2/eloquent-mutators
http://laravel.su/docs/5.2/eloquent-serialization

**Comment by greabock** [comment]
Этот проект надо полностью выпиливать и делать заново

**Comment by SerafimArts** [comment]
@VladShcherbin задача не относится к проекту нового сайта, пожалуйста, не делай так =\

**Comment by vladshcherbin** [comment]
@SerafimArts current твой никто же исправлять не будет, поэтому с 2.0 она пропадёт

**Comment by SerafimArts** [comment]
@VladShcherbin ну тогда закрыть её нафиг, сказать что будет всё ок в новой версии =)

**Comment by SerafimArts** [comment]
И да, current не мой ;)

**Comment by vladshcherbin** [comment]
@SerafimArts я думал с 2.0 и закрыть их =/

**Comment by SerafimArts** [comment]
Ну так чтобы 2.0 закрыть, надо все задачи выполнить =)

**Comment by vladshcherbin** [comment]
@SerafimArts ну так да, в 2.0 то 404 документации не будет надеюсь)

**Comment by SerafimArts** [comment]
@VladShcherbin короче, так и поступим, всё, что касается текущего сайта - просто закроем?
