### ISSUE TITLE
Password check fails when user is trying to register

### ISSUE THREAD

**Issue by vladshcherbin** [LaravelRUS/laravel.ru#18]
Password is set, but the error is still there.

> Поле password обязательно для заполнения.

**Comment by SerafimArts** [comment]
@VladShcherbin не забывай указывать версию (или ветку), сайтов несколько просто =)

**Comment by vladshcherbin** [comment]
@SerafimArts add a label for a new version please ;)

**Comment by SerafimArts** [comment]
Fixed https://github.com/LaravelRUS/laravel.ru/commit/d1215e640576937de6ab1f59ca6fc1314cfe96fa
