### ISSUE TITLE
Weird html tags when reloading articles page

### ISSUE THREAD

**Issue by vladshcherbin** [LaravelRUS/laravel.ru#43]
<details>
 <summary>Image</summary>

  ![image](https://cloud.githubusercontent.com/assets/6711845/23334048/094ee004-fba8-11e6-943a-69de65acab20.png)
</details>

**Comment by SerafimArts** [comment]
https://github.com/LaravelRUS/laravel.ru/commit/2edebe9f33ee42ca89578dd7a639c946ec432d2e
