### ISSUE TITLE
Graphql API

### ISSUE THREAD

**Issue by Ljay-ru** [LaravelRUS/laravel.ru#52]
При скроллинге постов ( https://new.laravel.su/articles )

Данные могут просто закончится, но приложение об этом знать не будет, и кнопочка "еще" будет показыватся, а при клике будет возвращать пустой массив, т.к никакой инфы от апи по поводу текущий страницы, как например, в дефолтном пагинаторе - нет.

Нужно возвращать количество страниц, для того что бы можно было прятать кнопку.

Так же ссылка в readme.md насчет перевода - мертвая.

**Comment by SerafimArts** [comment]
> Так же ссылка в readme.md насчет перевода - мертвая.

Какого перевода? <_<

**Comment by Ljay-ru** [comment]
Вот тут - https://github.com/LaravelRUS/laravel.ru )
Помощь -> Инструкция, как это делать правильно.

**Comment by SerafimArts** [comment]
> Так же ссылка в readme.md насчет перевода - мертвая.

Исправления для master ветки: https://github.com/LaravelRUS/laravel.ru/commit/497bf9008c8cc7a6b59530e062920b36e979578f

Исправления для ветки feature-laravel-5.4: https://github.com/LaravelRUS/laravel.ru/commit/fbe3e4c135aa9e593395113a6090cd18db2b6380

@Ljay-ru думаю стоит в следующий раз создавать разные issue для разных задач =)

**Comment by Ljay-ru** [comment]
@SerafimArts Понял, сорян :x

**Comment by vladshcherbin** [comment]
Исправлено в react версии.
