### ISSUE TITLE
Поле пароль пропадает при обновлении страницы логин

### ISSUE THREAD

**Issue by vladshcherbin** [LaravelRUS/laravel.ru#66]
При обновлении страницы https://new.laravel.su/login, поле пароль куда-то пропадает, а потом появляется.

**Comment by vladshcherbin** [comment]
Аналогично на странице регистрации.

**Comment by SerafimArts** [comment]
У меня везде всё ок. Мб из-за виртуального элемента пароля? Но там страница лочится (полупрозрачная) до рендера этого поля.

**Comment by vladshcherbin** [comment]
@SerafimArts 


[nl.mp4.zip](https://github.com/LaravelRUS/laravel.ru/files/815650/nl.mp4.zip)

**Comment by SerafimArts** [comment]
Ну как я и говорил, из-за виртуального элемента: https://github.com/LaravelRUS/laravel.ru/blob/feature-laravel-5.4/resources/views/page/auth/login.blade.php#L17 он рендерится отложенно, вне контекста. Вот когда ты будешь фронтэндером и перепишешь всё на реакт - поправишь же? =)))

**Comment by vladshcherbin** [comment]
@SerafimArts мне докер сказал давай до свидания ещё на стадии запуска проекта 😭

**Comment by SerafimArts** [comment]
@VladShcherbin создай иссью с докером, опиши ошибку, маленький чтоль? =))))

**Comment by vladshcherbin** [comment]
@SerafimArts да я думал почитать в гугле, как пофиксить (там по идее с правами или с бд доступом что-то), да тут эта задача с бд магазина весь мозг проела 😢 🤕

**Comment by vladshcherbin** [comment]
Исправлено в ветке реакта.
