### ISSUE TITLE
Добавить cors

### ISSUE THREAD

**Issue by vladshcherbin** [LaravelRUS/laravel.ru#67]
Для запросов с клиента на серверную часть.

**Comment by SerafimArts** [comment]
Сделал по-быстрому: https://github.com/LaravelRUS/laravel.ru/commit/1375010ee3906a9a92c24903a91547112f98a0af

**Comment by vladshcherbin** [comment]
Пока что не работает. #feelsBadMan

**Comment by SerafimArts** [comment]
не работает OPTIONS запрос. В твоих требованиях его не было. Как задача поставлена, так она и выполнена+ 

:D
