### ISSUE TITLE
Изменить graphQl пагинацию на курсоровую

### ISSUE THREAD

**Issue by vladshcherbin** [LaravelRUS/laravel.ru#68]
Текущая пагинация не точна ввиду её особенностей.

**Comment by vladshcherbin** [comment]
https://github.com/LaravelRUS/laravel.ru/issues/52

**Comment by vladshcherbin** [comment]
Само описание, раздел `Cursor-based pagination` или `Relay cursor connections`, оба варианта поддерживаются на клиенте

https://dev-blog.apollodata.com/understanding-pagination-rest-graphql-and-relay-b10f835549e7#.8byevox1d

**Comment by SerafimArts** [comment]
https://github.com/LaravelRUS/laravel.ru/commit/df9ab33fb2c8143a2d6d611d04ef65c9389187a6
