### ISSUE TITLE
Запросы в GraphQl 

### ISSUE THREAD

**Issue by vladshcherbin** [LaravelRUS/laravel.ru#71]
```graphql
query singleArticle {
  articles(id: 2) {
    title
  }
}
```

Запрос вернёт массив, внутри которого будет статья с id = 2

Если я правильно понимаю, запрос `articles(id: [1, 3, 4])` должен возвращать массив со статьями, в то время как `article(id: 3)` - одну статью.

**Comment by vladshcherbin** [comment]
Второй вопрос - когда мы запрашиваем какие-то поля, как например выше поле `title` - из бд мы тянем всё равно же селектом все поля?

**Comment by SerafimArts** [comment]
> Если я правильно понимаю, запрос articles(id: [1, 3, 4]) должен возвращать массив со статьями, в то время как article(id: 3) - одну статью.

Ноуп. Запрос так я назвал и принудительно указал тип int в аргументах.

> Второй вопрос - когда мы запрашиваем какие-то поля, как например выше поле title - из бд мы тянем всё равно же селектом все поля?

Как реализовано - так и тянем. Реализовано "в лоб", т.е. всё. На текущих объёмах данных - это однофигственно.

**Comment by vladshcherbin** [comment]
> Ноуп. Запрос так я назвал и принудительно указал тип int в аргументах.

Это я понимаю, но нужно поменять `articles([ID]!)` - возвращает массив статей, `article(ID!)` - одна статья.

> Как реализовано - так и тянем. Реализовано "в лоб", т.е. всё. На текущих объёмах данных - это однофигственно.

Тут уже решение за тобой, как минимум странно зная нужные поля, тащить все. Но это, наверное, нормально в стране GraphQl 😕

**Comment by SerafimArts** [comment]
> Тут уже решение за тобой, как минимум странно зная нужные поля, тащить все. Но это, наверное, нормально в стране GraphQl

Это нормально, когда делается побыстрее.

> Это я понимаю, но нужно поменять articles([ID]!) - возвращает массив статей, article(ID!) - одна статья.

В Gql всегда возвращается массив, отличия только в том, что будет один элемент или несколько. По-этому не имеет никакого смысла делать ещё один ресурс, проще просто добавить поддержку поиска по массиву айди или одному айди.

**Comment by SerafimArts** [comment]
https://github.com/LaravelRUS/laravel.ru/commit/66d75b835123f22debb23e37ce8b22d0f1899797
