### ISSUE TITLE
Помогите запустить на 8080 порту

### ISSUE THREAD

**Issue by Telegramsrv** [LaravelRUS/laravel.ru#81]
Какие настройки в файлах поменять, чтоб запускать проект http://127.0.0.1:8080/articles#

**Comment by Telegramsrv** [comment]
я запускал, но затер файлы, и теперь не прокидывается порт

как хочу чтоб было
![photo_2017-05-07_13-36-57](https://cloud.githubusercontent.com/assets/22915282/25781170/94d132da-333e-11e7-9713-9965ee584430.jpg)

пока получается только нгингс вытащить

![photo_2017-05-07_15-40-12](https://cloud.githubusercontent.com/assets/22915282/25781180/b68be622-333e-11e7-85c6-44ea7399d01e.jpg)

**Comment by SerafimArts** [comment]
https://github.com/LaravelRUS/laravel.ru/blob/2.0/docker-compose.yml#L36
Заменить `443:443` на `443:8080`

**Comment by Telegramsrv** [comment]
до сих пор ковыряю, поднять не получается, больше точно не нужно нигде менять настройки?
default.conf или websocket.conf

**Comment by Telegramsrv** [comment]
вроде сделал default.conf - https://pastebin.com/ranA9YBX, websocket.conf - https://pastebin.com/3VEdD4rj

**Comment by SerafimArts** [comment]
> websocket.conf

такого файла уже давно не существует =)

**Comment by SerafimArts** [comment]
> вроде сделал default.conf

это говорит о внутреннем порте контейнера, а не о внешнем в твоей системе, так что не. Дальше порт прописывается в экспоуз (мол он публичный и может быть виден откуда угодно), а в "компоузе" прописывается маппинг, мол мы внутренний этот публичный порт прокидываем в нашу операционку под номером X (ссылку где этт маппинг делается я кинул выше).

**Comment by Telegramsrv** [comment]
да, еще прокидываю порты в Dockerfile nginx-а `EXPOSE 80 443 8080`
и в docker-compose.yml `80:80` `443:8080` `8080:8080`

да websocket.conf это старый файл

у меня все работает я рад, спасибо за помощь
`

**Comment by SerafimArts** [comment]
> 443:8080 8080:8080

И как у тебя 2 процесса будут занимать один и тот же порт? о_0

**Comment by smgladkovskiy** [comment]
Процесс один. Expose же идёт на 2 порта...

**Comment by SerafimArts** [comment]
У меня подозрение, что я перепутал просто внутренний и внешний порты :D
