### ISSUE TITLE
Ссылки на чат

### ISSUE THREAD

**Issue by tabuna** [LaravelRUS/laravel.ru#86]
На laravel.su в вернем и нижнем меню используются ссылки на gitter, а не на discord

**Comment by vladshcherbin** [comment]
@tabuna оба чата рабочие. Меню со списком было бы хорошим дополнением.

**Comment by SerafimArts** [comment]
Тогда надо бы и телегу не забыть.

**Comment by vladshcherbin** [comment]
@SerafimArts да

**Comment by SerafimArts** [comment]
@tabuna твой PR в проде, всё ок.
